# Generated by Django 3.0.6 on 2020-06-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200608_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='geo_lat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='geo_lon',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
