# Generated by Django 3.0.6 on 2020-06-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200609_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='geo_lat',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='geo_lon',
        ),
    ]
