# Generated by Django 3.0.6 on 2020-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200610_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lng',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
