# Generated by Django 3.0.6 on 2020-06-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200610_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
