# Generated by Django 3.0.6 on 2020-06-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.AddField(
            model_name='listing',
            name='region',
            field=models.CharField(choices=[('Attica', 'Attica'), ('Central Greece', 'Central Greece'), ('Central Macedonia', 'Central Macedonia'), ('Crete', 'Crete'), ('Eastern Macedonia', 'Eastern Macedonia'), ('Thrace', 'Thrace'), ('Epirus', 'Epirus'), ('Ionian Islands', 'Ionian Islands'), ('North Aegean', 'North Aegean'), ('Peloponnese', 'Peloponnese'), ('South Aegean', 'South Aegean'), ('Thessaly', 'Thessaly'), ('Western Greece', 'Western Greece'), ('Western Macedonia', 'Western Macedonia')], default='Attica', max_length=100),
        ),
    ]
