# Generated by Django 3.0.6 on 2020-06-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_listing_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.TextField(default='Attica'),
            preserve_default=False,
        ),
    ]
