# Generated by Django 3.0.6 on 2020-06-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20200621_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='lng',
        ),
    ]
