# Generated by Django 3.0.6 on 2020-06-24 20:42

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_remove_listing_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='hidden_address',
            field=mapbox_location_field.models.AddressAutoHiddenField(default=' '),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=mapbox_location_field.models.LocationField(default='Athens', map_attrs={}),
            preserve_default=False,
        ),
    ]
