# Generated by Django 3.0.6 on 2020-06-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20200624_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='hidden_address',
        ),
    ]
