# Generated by Django 3.0.6 on 2020-06-24 20:52

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_remove_listing_hidden_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [37, 23], 'marker_color': 'blue'}),
        ),
    ]
