# Generated by Django 3.0.6 on 2020-06-24 21:08

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_listing_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='hidden',
            field=mapbox_location_field.models.AddressAutoHiddenField(blank=True),
        ),
    ]
