# Generated by Django 3.0.6 on 2020-06-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20200627_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='geo_lat',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='geo_lng',
        ),
    ]
