# Generated by Django 3.0.6 on 2020-06-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20200627_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='geo_lat',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='listing',
            name='geo_lng',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=13),
        ),
    ]
