# Generated by Django 3.0.6 on 2020-06-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_auto_20200629_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Bungalow', 'Bungalow'), ('Flat/Appartment', 'Flat/Appartment'), ('Studio', 'Studio'), ('House', 'House'), ('Land', 'Land'), ('Commercial Property', 'Commercial Property')], default='House', max_length=100),
        ),
    ]
