# Generated by Django 3.0.6 on 2020-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_auto_20200629_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Flat/Appartment', 'Flat/Appartment'), ('Land', 'Land'), ('Bungalow', 'Bungalow'), ('Commercial Property', 'Commercial Property'), ('Studio', 'Studio'), ('House', 'House')], default='House', max_length=100),
        ),
    ]
