# Generated by Django 3.0.6 on 2020-06-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_auto_20200629_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Studio', 'Studio'), ('House', 'House'), ('Flat/Appartment', 'Flat/Appartment'), ('Bungalow', 'Bungalow'), ('Land', 'Land'), ('Commercial Property', 'Commercial Property')], default='House', max_length=100),
        ),
    ]
