import math

def round_down(n, decimals=0):
    multiplier = 10 ** decimals
    return math.floor(n * multiplier) / multiplier



property_type = (
  ('Studio','Studio'),
  ('House','House'),
  ('Flat/Appartment','Flat/Appartment'),
  ('Bungalow', 'Bungalow'),
  ('Land', 'Land'),
  ('Commercial Property','Commercial Property')
)

bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }



price_choices = {
  '50000':'50,000€',
  '80000':'80,000€',
  '100000':'100,000€',
  '200000':'200,000€',
  '300000':'300,000€',
  '400000':'400,000€',
  '500000':'500,000€',
  '600000':'600,000€',
  '700000':'700,000€',
  '800000':'800,000€',
  '900000':'900,000€',
  '1000000':'1M+€',
}

region_choices = {
        'Attica': 'Attica',
        'Central Greece': 'Central Greece',
        'Central Macedonia': 'Central Macedonia',
        'Crete': 'Crete',
        'Eastern Macedonia': 'Eastern Macedonia',
        'Thrace': 'Thrace',
        'Epirus': 'Epirus',
        'Ionian Islands': 'Ionian Islands',
        'North Aegean': 'North Aegean',
        'Peloponnese': 'Peloponnese',
        'South Aegean': 'South Aegean',
        'Thessaly': 'Thessaly',
        'Western Greece': 'Western Greece',
        'Western Macedonia': 'Western Macedonia',
}


city1_choices = {
    "Aegina":"Aegina",
    "Agioi Anargyroi":"Agioi Anargyroi",
    "Athens":"Athens",
}

city_choices = {
"Acharnes":"Acharnes",
"Aegina":"Aegina",
"Afantou":"Afantou",
"Agia Paraskevi":"Agia Paraskevi",
"Agia Varvara":"Agia Varvara",
"Agioi Anargyroi":"Agioi Anargyroi",
"Agios Dimitrios":"Agios Dimitrios",
"Agios Ioannis Rentis":"Agios Ioannis Rentis",
"Agios Nikolaos":"Agios Nikolaos",
"Agios Pavlos":"Agios Pavlos",
"Agios Stefanos":"Agios Stefanos",
"Agria":"Agria",
"Agrinio":"Agrinio",
"Aigaleo":"Aigaleo",
"Aigio":"Aigio",
"Alexandreia":"Alexandreia",
"Alexandroupoli":"Alexandroupoli",
"Alimos":"Alimos",
"Aliveri":"Aliveri",
"Almyros":"Almyros",
"Amaliada":"Amaliada",
"Amfissa":"Amfissa",
"Ampelona":"Ampelona",
"Anatoli":"Anatoli",
"Anavyssos":"Anavyssos",
"Ano Liosia":"Ano Liosia",
"Anoixi":"Anoixi",
"Archangelos":"Archangelos",
"Argos":"Argos",
"Argos Orestiko":"Argos Orestiko",
"Argostolion":"Argostolion",
"Argyroupoli":"Argyroupoli",
"Aridaia":"Aridaia",
"Arta":"Arta",
"Artemida":"Artemida",
"Aspropyrgos":"Aspropyrgos",
"Asvestochori":"Asvestochori",
"Athens":"Athens",
"Avlonas":"Avlonas",
"Ayios Konstandinos":"Ayios Konstandinos",
"Chaidari":"Chaidari",
"Chalastra":"Chalastra",
"Chalkida":"Chalkida",
"Chania":"Chania",
"Chios":"Chios",
"Cholargos":"Cholargos",
"Chrysoupolis":"Chrysoupolis",
"Corfu":"Corfu",
"Dhafni":"Dhafni",
"Dhrosia":"Dhrosia",
"Diavata":"Diavata",
"Didymoteicho":"Didymoteicho",
"Dionysos":"Dionysos",
"Drama":"Drama",
"Drapetsona":"Drapetsona",
"Drosia":"Drosia",
"Edessa":"Edessa",
"Ekali":"Ekali",
"Elassona":"Elassona",
"Elefsina":"Elefsina",
"Elliniko":"Elliniko",
"Epanomi":"Epanomi",
"Ermoupolis":"Ermoupolis",
"Faliraki":"Faliraki",
"Farsala":"Farsala",
"Feres":"Feres",
"Filiatra":"Filiatra",
"Filothei":"Filothei",
"Florina":"Florina",
"Galatsi":"Galatsi",
"Gargalianoi":"Gargalianoi",
"Gastouni":"Gastouni",
"Gazi":"Gazi",
"Gerakas":"Gerakas",
"Giannitsa":"Giannitsa",
"Giannouli":"Giannouli",
"Glyfada":"Glyfada",
"Grevena":"Grevena",
"Ialysos":"Ialysos",
"Ierapetra":"Ierapetra",
"Igoumenitsa":"Igoumenitsa",
"Ilion":"Ilion",
"Ilioupoli":"Ilioupoli",
"Ioannina":"Ioannina",
"Irakleio":"Irakleio",
"Irakleion":"Irakleion",
"Kaisariani":"Kaisariani",
"Kalamaria":"Kalamaria",
"Kalamata":"Kalamata",
"Kalampaka":"Kalampaka",
"Kallithea":"Kallithea",
"Kalymnos":"Kalymnos",
"Kalyvia Thorikou":"Kalyvia Thorikou",
"Kamateron":"Kamateron",
"Karditsa":"Karditsa",
"Karpenisi":"Karpenisi",
"Karyes":"Karyes",
"Karystos":"Karystos",
"Kastoria":"Kastoria",
"Katerini":"Katerini",
"Kato Achaia":"Kato Achaia",
"Kavala":"Kavala",
"Keratea":"Keratea",
"Keratsini":"Keratsini",
"Khalandrion":"Khalandrion",
"Kiato":"Kiato",
"Kifisia":"Kifisia",
"Kilkis":"Kilkis",
"Komotini":"Komotini",
"Korinthos":"Korinthos",
"Koropi":"Koropi",
"Korydallos":"Korydallos",
"Kos":"Kos",
"Koufalia":"Koufalia",
"Kozani":"Kozani",
"Krya Vrysi":"Krya Vrysi",
"Kryoneri":"Kryoneri",
"Kyparissia":"Kyparissia",
"Lagkadas":"Lagkadas",
"Lamia":"Lamia",
"Larisa":"Larisa",
"Lavrio":"Lavrio",
"Lefkada":"Lefkada",
"Leondarion":"Leondarion",
"Limin Mesoyaias":"Limin Mesoyaias",
"Litochoro":"Litochoro",
"Livadeia":"Livadeia",
"Loutraki":"Loutraki",
"Lykovrysi":"Lykovrysi",
"Mandra":"Mandra",
"Marathonas":"Marathonas",
"Markopoulo":"Markopoulo",
"Marousi":"Marousi",
"Megalopoli":"Megalopoli",
"Megara":"Megara",
"Melissia":"Melissia",
"Menemeni":"Menemeni",
"Mesolongi":"Mesolongi",
"Messini":"Messini",
"Metamorfosi":"Metamorfosi",
"Moires":"Moires",
"Moskhaton":"Moskhaton",
"Mournies":"Mournies",
"Myrina":"Myrina",
"Mytilene":"Mytilene",
"Nafpaktos":"Nafpaktos",
"Nafplio":"Nafplio",
"Naousa":"Naousa",
"Naxos":"Naxos",
"Nea Alikarnassos":"Nea Alikarnassos",
"Nea Anchialos":"Nea Anchialos",
"Nea Artaki":"Nea Artaki",
"Nea Chalkidona":"Nea Chalkidona",
"Nea Erythraia":"Nea Erythraia",
"Nea Filadelfeia":"Nea Filadelfeia",
"Nea Ionia":"Nea Ionia",
"Nea Ionia":"Nea Ionia",
"Nea Kallikrateia":"Nea Kallikrateia",
"Nea Makri":"Nea Makri",
"Nea Michaniona":"Nea Michaniona",
"Nea Moudhania":"Nea Moudhania",
"Nea Penteli":"Nea Penteli",
"Nea Peramos":"Nea Peramos",
"Nea Smyrni":"Nea Smyrni",
"Neapoli":"Neapoli",
"Neo Psychiko":"Neo Psychiko",
"Neoi Epivates":"Neoi Epivates",
"Neon Karlovasion":"Neon Karlovasion",
"Nikaia":"Nikaia",
"Oraiokastro":"Oraiokastro",
"Orchomenos":"Orchomenos",
"Orestiada":"Orestiada",
"Ovria":"Ovria",
"Paiania":"Paiania",
"Palaio Faliro":"Palaio Faliro",
"Palamas":"Palamas",
"Pallini":"Pallini",
"Panorama":"Panorama",
"Papagou":"Papagou",
"Paralia":"Paralia",
"Paros":"Paros",
"Patra":"Patra",
"Pefki":"Pefki",
"Peraia":"Peraia",
"Perama":"Perama",
"Peristeri":"Peristeri",
"Petroupolis":"Petroupolis",
"Piraeus":"Piraeus",
"Plagiari":"Plagiari",
"Polichni":"Polichni",
"Polygyros":"Polygyros",
"Polykastro":"Polykastro",
"Preveza":"Preveza",
"Psachna":"Psachna",
"Psychiko":"Psychiko",
"Ptolemaida":"Ptolemaida",
"Pylaia":"Pylaia",
"Pyrgos":"Pyrgos",
"Rafina":"Rafina",
"Rethymno":"Rethymno",
"Rodos":"Rodos",
"Salamina":"Salamina",
"Serres":"Serres",
"Siatista":"Siatista",
"Sidirokastro":"Sidirokastro",
"Sindos":"Sindos",
"Sitia":"Sitia",
"Skiathos":"Skiathos",
"Souda":"Souda",
"Sparti":"Sparti",
"Spata":"Spata",
"Sykies":"Sykies",
"Tavros":"Tavros",
"Thermi":"Thermi",
"Thessaloniki":"Thessaloniki",
"Thivai":"Thivai",
"Thrakomakedones":"Thrakomakedones",
"Triandria":"Triandria",
"Trikala":"Trikala",
"Trilofos":"Trilofos",
"Tripoli":"Tripoli",
"Tympaki":"Tympaki",
"Tyrnavos":"Tyrnavos",
"Vari":"Vari",
"Vasilikon":"Vasilikon",
"Veroia":"Veroia",
"Volos":"Volos",
"Voula":"Voula",
"Vrilissia":"Vrilissia",
"Vrontados":"Vrontados",
"Vyronas":"Vyronas",
"Xanthi":"Xanthi",
"Xylokastro":"Xylokastro",
"Ymittos":"Ymittos",
"Zacharo":"Zacharo",
"Zakynthos":"Zakynthos",
"Zefyri":"Zefyri",
"Zografos":"Zografos",


}

city_model = (

("Acharnes","Acharnes"),
("Aegina","Aegina"),
("Afantou","Afantou"),
("Agia Paraskevi","Agia Paraskevi"),
("Agia Varvara","Agia Varvara"),
("Agioi Anargyroi","Agioi Anargyroi"),
("Agios Dimitrios","Agios Dimitrios"),
("Agios Ioannis Rentis","Agios Ioannis Rentis"),
("Agios Nikolaos","Agios Nikolaos"),
("Agios Pavlos","Agios Pavlos"),
("Agios Stefanos","Agios Stefanos"),
("Agria","Agria"),
("Agrinio","Agrinio"),
("Aigaleo","Aigaleo"),
("Aigio","Aigio"),
("Alexandreia","Alexandreia"),
("Alexandroupoli","Alexandroupoli"),
("Alimos","Alimos"),
("Aliveri","Aliveri"),
("Almyros","Almyros"),
("Amaliada","Amaliada"),
("Amfissa","Amfissa"),
("Ampelona","Ampelona"),
("Anatoli","Anatoli"),
("Anavyssos","Anavyssos"),
("Ano Liosia","Ano Liosia"),
("Anoixi","Anoixi"),
("Archangelos","Archangelos"),
("Argos","Argos"),
("Argos Orestiko","Argos Orestiko"),
("Argostolion","Argostolion"),
("Argyroupoli","Argyroupoli"),
("Aridaia","Aridaia"),
("Arta","Arta"),
("Artemida","Artemida"),
("Aspropyrgos","Aspropyrgos"),
("Asvestochori","Asvestochori"),
("Athens","Athens"),
("Avlonas","Avlonas"),
("Ayios Konstandinos","Ayios Konstandinos"),
("Chaidari","Chaidari"),
("Chalastra","Chalastra"),
("Chalkida","Chalkida"),
("Chania","Chania"),
("Chios","Chios"),
("Cholargos","Cholargos"),
("Chrysoupolis","Chrysoupolis"),
("Corfu","Corfu"),
("Dhafni","Dhafni"),
("Dhrosia","Dhrosia"),
("Diavata","Diavata"),
("Didymoteicho","Didymoteicho"),
("Dionysos","Dionysos"),
("Drama","Drama"),
("Drapetsona","Drapetsona"),
("Drosia","Drosia"),
("Edessa","Edessa"),
("Ekali","Ekali"),
("Elassona","Elassona"),
("Elefsina","Elefsina"),
("Elliniko","Elliniko"),
("Epanomi","Epanomi"),
("Ermoupolis","Ermoupolis"),
("Faliraki","Faliraki"),
("Farsala","Farsala"),
("Feres","Feres"),
("Filiatra","Filiatra"),
("Filothei","Filothei"),
("Florina","Florina"),
("Galatsi","Galatsi"),
("Gargalianoi","Gargalianoi"),
("Gastouni","Gastouni"),
("Gazi","Gazi"),
("Gerakas","Gerakas"),
("Giannitsa","Giannitsa"),
("Giannouli","Giannouli"),
("Glyfada","Glyfada"),
("Grevena","Grevena"),
("Ialysos","Ialysos"),
("Ierapetra","Ierapetra"),
("Igoumenitsa","Igoumenitsa"),
("Ilion","Ilion"),
("Ilioupoli","Ilioupoli"),
("Ioannina","Ioannina"),
("Irakleio","Irakleio"),
("Irakleion","Irakleion"),
("Kaisariani","Kaisariani"),
("Kalamaria","Kalamaria"),
("Kalamata","Kalamata"),
("Kalampaka","Kalampaka"),
("Kallithea","Kallithea"),
("Kalymnos","Kalymnos"),
("Kalyvia Thorikou","Kalyvia Thorikou"),
("Kamateron","Kamateron"),
("Karditsa","Karditsa"),
("Karpenisi","Karpenisi"),
("Karyes","Karyes"),
("Karystos","Karystos"),
("Kastoria","Kastoria"),
("Katerini","Katerini"),
("Kato Achaia","Kato Achaia"),
("Kavala","Kavala"),
("Keratea","Keratea"),
("Keratsini","Keratsini"),
("Khalandrion","Khalandrion"),
("Kiato","Kiato"),
("Kifisia","Kifisia"),
("Kilkis","Kilkis"),
("Komotini","Komotini"),
("Korinthos","Korinthos"),
("Koropi","Koropi"),
("Korydallos","Korydallos"),
("Kos","Kos"),
("Koufalia","Koufalia"),
("Kozani","Kozani"),
("Krya Vrysi","Krya Vrysi"),
("Kryoneri","Kryoneri"),
("Kyparissia","Kyparissia"),
("Lagkadas","Lagkadas"),
("Lamia","Lamia"),
("Larisa","Larisa"),
("Lavrio","Lavrio"),
("Lefkada","Lefkada"),
("Leondarion","Leondarion"),
("Limin Mesoyaias","Limin Mesoyaias"),
("Litochoro","Litochoro"),
("Livadeia","Livadeia"),
("Loutraki","Loutraki"),
("Lykovrysi","Lykovrysi"),
("Mandra","Mandra"),
("Marathonas","Marathonas"),
("Markopoulo","Markopoulo"),
("Marousi","Marousi"),
("Megalopoli","Megalopoli"),
("Megara","Megara"),
("Melissia","Melissia"),
("Menemeni","Menemeni"),
("Mesolongi","Mesolongi"),
("Messini","Messini"),
("Metamorfosi","Metamorfosi"),
("Moires","Moires"),
("Moskhaton","Moskhaton"),
("Mournies","Mournies"),
("Myrina","Myrina"),
("Mytilene","Mytilene"),
("Nafpaktos","Nafpaktos"),
("Nafplio","Nafplio"),
("Naousa","Naousa"),
("Naxos","Naxos"),
("Nea Alikarnassos","Nea Alikarnassos"),
("Nea Anchialos","Nea Anchialos"),
("Nea Artaki","Nea Artaki"),
("Nea Chalkidona","Nea Chalkidona"),
("Nea Erythraia","Nea Erythraia"),
("Nea Filadelfeia","Nea Filadelfeia"),
("Nea Ionia","Nea Ionia"),
("Nea Ionia","Nea Ionia"),
("Nea Kallikrateia","Nea Kallikrateia"),
("Nea Makri","Nea Makri"),
("Nea Michaniona","Nea Michaniona"),
("Nea Moudhania","Nea Moudhania"),
("Nea Penteli","Nea Penteli"),
("Nea Peramos","Nea Peramos"),
("Nea Smyrni","Nea Smyrni"),
("Neapoli","Neapoli"),
("Neo Psychiko","Neo Psychiko"),
("Neoi Epivates","Neoi Epivates"),
("Neon Karlovasion","Neon Karlovasion"),
("Nikaia","Nikaia"),
("Oraiokastro","Oraiokastro"),
("Orchomenos","Orchomenos"),
("Orestiada","Orestiada"),
("Ovria","Ovria"),
("Paiania","Paiania"),
("Palaio Faliro","Palaio Faliro"),
("Palamas","Palamas"),
("Pallini","Pallini"),
("Panorama","Panorama"),
("Papagou","Papagou"),
("Paralia","Paralia"),
("Paros","Paros"),
("Patra","Patra"),
("Pefki","Pefki"),
("Peraia","Peraia"),
("Perama","Perama"),
("Peristeri","Peristeri"),
("Petroupolis","Petroupolis"),
("Piraeus","Piraeus"),
("Plagiari","Plagiari"),
("Polichni","Polichni"),
("Polygyros","Polygyros"),
("Polykastro","Polykastro"),
("Preveza","Preveza"),
("Psachna","Psachna"),
("Psychiko","Psychiko"),
("Ptolemaida","Ptolemaida"),
("Pylaia","Pylaia"),
("Pyrgos","Pyrgos"),
("Rafina","Rafina"),
("Rethymno","Rethymno"),
("Rodos","Rodos"),
("Salamina","Salamina"),
("Serres","Serres"),
("Siatista","Siatista"),
("Sidirokastro","Sidirokastro"),
("Sindos","Sindos"),
("Sitia","Sitia"),
("Skiathos","Skiathos"),
("Souda","Souda"),
("Sparti","Sparti"),
("Spata","Spata"),
("Sykies","Sykies"),
("Tavros","Tavros"),
("Thermi","Thermi"),
("Thessaloniki","Thessaloniki"),
("Thivai","Thivai"),
("Thrakomakedones","Thrakomakedones"),
("Triandria","Triandria"),
("Trikala","Trikala"),
("Trilofos","Trilofos"),
("Tripoli","Tripoli"),
("Tympaki","Tympaki"),
("Tyrnavos","Tyrnavos"),
("Vari","Vari"),
("Vasilikon","Vasilikon"),
("Veroia","Veroia"),
("Volos","Volos"),
("Voula","Voula"),
("Vrilissia","Vrilissia"),
("Vrontados","Vrontados"),
("Vyronas","Vyronas"),
("Xanthi","Xanthi"),
("Xylokastro","Xylokastro"),
("Ymittos","Ymittos"),
("Zacharo","Zacharo"),
("Zakynthos","Zakynthos"),
("Zefyri","Zefyri"),
("Zografos","Zografos"),


)

region_model = (
        ('Attica', 'Attica'),
        ('Central Greece', 'Central Greece'),
        ('Central Macedonia', 'Central Macedonia'),
        ('Crete', 'Crete'),
        ('Eastern Macedonia', 'Eastern Macedonia'),
        ('Thrace', 'Thrace'),
        ('Epirus', 'Epirus'),
        ('Ionian Islands', 'Ionian Islands'),
        ('North Aegean', 'North Aegean'),
        ('Peloponnese', 'Peloponnese'),
        ('South Aegean', 'South Aegean'),
        ('Thessaly', 'Thessaly'),
        ('Western Greece', 'Western Greece'),
        ('Western Macedonia', 'Western Macedonia'),
)

